### PR TITLE
adding some tests

### PR DESCRIPTION
**Pull request by igorgcosta**
Adding some tests, to run "npm test", after install dependencies.

### CODE REVIEW

**Comment by grikomsn** [comment]
Thanks for the contribution, @igorgcosta! I'll wrap up #17 then merge this afterwards. You could help review PR #17 and tell your insights. 🎉

**Comment by igorgcosta** [comment]
Grikomsn, I would like to suggest some changes on index code to better test cases. I can send a PR if you're interested

**Comment by grikomsn** [comment]
> @grikomsn, I would like to suggest some changes on index code to better test cases. I can send a PR if you're interested

I just merged #17, do send your PR and I'll review it ✨

**Comment by igorgcosta** [comment]
> @igorgcosta, heads up: #21 has been merged and now Travis CI will use your test spec.

Nice!

**Comment by fpereira1** [comment]
@igorgcosta there are some tests failing, are you able to fix them?

**Comment by fpereira1** [comment]
It can be merged once mocha tests are passing

**Comment by igorgcosta** [comment]
Hi @fpereira1, what's tests are failing?

**Comment by fpereira1** [comment]
hey @igorgcosta - the mocha tests are failing.  See https://travis-ci.com/grikomsn/rotten-reviews/jobs/153122189#L520-L665

**Comment by vimark1** [comment]
hey @igorgcosta - I have fixed those tests and will be merging in a separate PR. 
 Thanks! https://github.com/grikomsn/rotten-reviews/pull/59

**Pull request closed without merging**
